### 1. Importar las librerias 

In [2]:
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt
import time
import mediapipe as mp

### 2. Mediapipe holistics 

In [5]:
mp_holistic = mp.solutions.holistic # Holistic model
mp_drawing = mp.solutions.drawing_utils # Drawing utilities

In [7]:
def mediapipe_detection(image, model):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # COLOR CONVERSION BGR 2 RGB
    image.flags.writeable = False                  # Image is no longer writeable
    results = model.process(image)                 # Make prediction
    image.flags.writeable = True                   # Image is now writeable 
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR) # COLOR COVERSION RGB 2 BGR
    return image, results

In [9]:
def draw_landmarks(image, results):
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw right hand connections

In [11]:
def draw_styled_landmarks(image, results):
    # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                             ) 
    # Draw right hand connections  
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                             ) 

In [ ]:
cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()

        # Make detections
        image, results = mediapipe_detection(frame, holistic)
        print(results)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)

        # Show to screen
        cv2.imshow('OpenCV Feed', image)

        # Break gracefully
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

In [14]:
draw_landmarks(frame, results)

In [ ]:
plt.imshow(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))

### 3. Extraer los valores de los puntos clave

In [20]:
#len(results.right_hand_landmarks.landmark)

In [22]:
lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)

In [24]:
lh

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
def extract_keypoints(results):
    lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
    rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)
    return np.concatenate([lh, rh])

In [28]:
21*3+21*3

126

In [30]:
result_test = extract_keypoints(results)

In [32]:
result_test

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.save('0', result_test)

In [36]:
np.load('0.npy')

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

### 4. Recoleccion de imagenes 

In [41]:
# Path for exported data, numpy arrays
DATA_PATH = os.path.join('MP_Data') 

# Actions that we try to detect
actions = np.array(['A','B','C','D','E','F','G','H','I', 
                    'K','L','M','N','Ñ','O','P','Q','R','S','T',
                    'U','V','W','X','Y','Z']) #26

# Thirty videos worth of data
no_sequences = 30

# Videos are going to be 30 frames in length
sequence_length = 30

# Folder start
start_folder = 30

In [43]:
for action in actions: 
    for sequence in range(1,no_sequences+1):
        try: 
            os.makedirs(os.path.join(DATA_PATH, action, str(sequence)))
        except:
            pass

### 5. Recolectar valor de los puntos clave para entrenamiento 

In [ ]:
cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    
    # NEW LOOP
    # Loop through actions
    for action in actions:
        # Loop through sequences aka videos
        for sequence in range(no_sequences):
            # Loop through video length aka sequence length
            for frame_num in range(sequence_length):

                # Read feed
                ret, frame = cap.read()

                # Make detections
                image, results = mediapipe_detection(frame, holistic)
#                 print(results)

                # Draw landmarks
                draw_styled_landmarks(image, results)
                
                # NEW Apply wait logic
                if frame_num == 0: 
                    cv2.putText(image, 'STARTING COLLECTION', (120,200), 
                               cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv2.LINE_AA)
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', image)
                    cv2.waitKey(1000)
                else: 
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', image)
                
                # NEW Export keypoints
                keypoints = extract_keypoints(results)
                npy_path = os.path.join(DATA_PATH, action, str(sequence))
                os.makedirs(npy_path, exist_ok=True)  # Ensure directories exist
                
                file_path = os.path.join(npy_path, f"{frame_num}.npy")
                np.save(file_path, keypoints)

                # Break gracefully
                if cv2.waitKey(10) & 0xFF == ord('q'):
                    break
                    
    cap.release()
    cv2.destroyAllWindows()

In [56]:
cap.release()
cv2.destroyAllWindows()

### 6. Preprocesar datos y crear labels 

In [110]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical 

In [111]:
label_map = {label:num for num, label in enumerate (actions)}

In [112]:
label_map

{'A': 0,
 'B': 1,
 'C': 2,
 'D': 3,
 'E': 4,
 'F': 5,
 'G': 6,
 'H': 7,
 'I': 8,
 'K': 9,
 'L': 10,
 'M': 11,
 'N': 12,
 'Ñ': 13,
 'O': 14,
 'P': 15,
 'Q': 16,
 'R': 17,
 'S': 18,
 'T': 19,
 'U': 20,
 'V': 21,
 'W': 22,
 'X': 23,
 'Y': 24,
 'Z': 25}

In [113]:
sequences, labels = [], []
for action in actions:
    for sequence in range(no_sequences):
        window = []
        for frame_num in range(sequence_length):
            res = np.load(os.path.join(DATA_PATH, action, str(sequence), "{}.npy".format(frame_num)))
            window.append(res)
        sequences.append(window)
        labels.append(label_map[action])

In [114]:
np.array(sequences).shape

(780, 30, 126)

In [115]:
np.array(labels).shape

(780,)

In [116]:
X = np.array(sequences)

In [117]:
X.shape

(780, 30, 126)

In [118]:
y = to_categorical(labels).astype(int)

In [119]:
y

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1]])

In [120]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05)

In [121]:
y_test.shape

(39, 26)

### 7. Entrenar la Red Neuronal LSTM

In [123]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Input
from tensorflow.keras.callbacks import TensorBoard

In [124]:
log_dir = os.path.join('Logs')
tb_callback = TensorBoard(log_dir=log_dir)

In [125]:
model = Sequential([
    Input(shape=(30, 126)),  
    LSTM(64, return_sequences=True, activation='relu'),
    LSTM(128, return_sequences=True, activation='relu'),
    LSTM(64, return_sequences=False, activation='relu'),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(actions.shape[0], activation='softmax')
])


In [126]:
res = np.random.uniform(0.05, 0.2, 26)  # Genera 26 valores aleatorios
res = res / res.sum()  # Normaliza la suma a 1
print(sum(res))  # La suma será 1.0
print(res)

1.0
[0.04460428 0.04479767 0.0576524  0.04562925 0.04827354 0.02578998
 0.042306   0.03056825 0.02781153 0.01890103 0.04383292 0.01952959
 0.06340212 0.02673585 0.02768935 0.04575835 0.02574416 0.01962441
 0.04211662 0.04110023 0.06229686 0.04866484 0.03187792 0.02287749
 0.06007111 0.03234423]


In [127]:
actions[np.argmax(res)]

'N'

In [128]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])

In [129]:
model.fit(X_train, y_train, epochs=500, callbacks=[tb_callback])

Epoch 1/510
24/24 ━━━━━━━━━━━━━━━━━━━━ 7s 50ms/step - categorical_accuracy: 0.0649 - loss: 3.2122
Epoch 2/510
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - categorical_accuracy: 0.1056 - loss: 3.0349
Epoch 3/510
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 47ms/step - categorical_accuracy: 0.1259 - loss: 2.8582
Epoch 4/510
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - categorical_accuracy: 0.0991 - loss: 2.7216
Epoch 5/510
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - categorical_accuracy: 0.1166 - loss: 2.8251
Epoch 6/510
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - categorical_accuracy: 0.1500 - loss: 2.6048
Epoch 7/510
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 49ms/step - categorical_accuracy: 0.1844 - loss: 2.4894
Epoch 8/510
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - categorical_accuracy: 0.2671 - loss: 2.2801
Epoch 9/510
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 48ms/step - categorical_accuracy: 0.2848 - loss: 2.1682
Epoch 10/510
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 50ms/step - categorical_accuracy: 0.3050 - loss: 1.9936
Epoch 11/510
24/24 

In [130]:
model.summary()

### 8. Predicciones

In [132]:
res = model.predict(X_test)

In [133]:
actions[np.argmax(res[2])]

In [134]:
actions[np.argmax(y_test[4])]

### 9. Salvar archivo de pesos

In [136]:
model.save('best4.keras')

In [137]:
model.load_weights('best.keras')

### 10. Evaluar usando Confusion Matrix and Accuracy

In [139]:
from sklearn.metrics import multilabel_confusion_matrix, accuracy_score

In [140]:
yhat = model.predict(X_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 835ms/step


In [141]:
ytrue = np.argmax(y_test, axis=1).tolist()
yhat = np.argmax(yhat, axis=1).tolist()

In [142]:
multilabel_confusion_matrix(ytrue, yhat)

array([[[36,  0],
        [ 1,  2]],

       [[37,  0],
        [ 1,  1]],

       [[36,  0],
        [ 0,  3]],

       [[37,  0],
        [ 0,  2]],

       [[38,  1],
        [ 0,  0]],

       [[37,  0],
        [ 1,  1]],

       [[38,  0],
        [ 0,  1]],

       [[38,  0],
        [ 0,  1]],

       [[36,  0],
        [ 0,  3]],

       [[38,  0],
        [ 1,  0]],

       [[37,  1],
        [ 1,  0]],

       [[36,  1],
        [ 1,  1]],

       [[36,  1],
        [ 1,  1]],

       [[38,  0],
        [ 0,  1]],

       [[38,  0],
        [ 0,  1]],

       [[38,  0],
        [ 0,  1]],

       [[37,  0],
        [ 0,  2]],

       [[38,  1],
        [ 0,  0]],

       [[34,  0],
        [ 1,  4]],

       [[34,  3],
        [ 0,  2]],

       [[37,  0],
        [ 0,  2]],

       [[38,  0],
        [ 0,  1]],

       [[38,  0],
        [ 0,  1]]], dtype=int64)

In [143]:
accuracy_score(ytrue, yhat)

0.7948717948717948

### 11. Probar en Tiempo Real

In [145]:
from scipy import stats

In [2]:
# colors = [
#     (245, 117, 16), (117, 245, 16), (16, 117, 245), 
#     (245, 16, 117), (16, 245, 117), (117, 16, 245), 
#     (200, 200, 50), (50, 200, 200), (200, 50, 200)
# ]

# def prob_viz(res, actions, input_frame, colors):
#     output_frame = input_frame.copy()
    
#     bar_height = 25  # Adjust the height of each bar
#     text_y_offset = 10  # Offset for text to fit within the smaller bars
#     font_scale = 0.6  # Smaller font scale for labels
#     thickness = 1  # Thinner text

#     for num, prob in enumerate(res):
#         # Adjust the bar size (width and height)
#         bar_width = int(prob * 80)  # Smaller width scale, 80 instead of 100
#         cv2.rectangle(output_frame, (0, 60 + num * (bar_height + 10)), 
#                       (bar_width, 60 + num * (bar_height + 10) + bar_height), colors[num], -1)
        
#         # Adjust the font size for the labels
#         cv2.putText(output_frame, actions[num], (0, 60 + num * (bar_height + 10) + text_y_offset), 
#                     cv2.FONT_HERSHEY_SIMPLEX, font_scale, (255, 255, 255), thickness, cv2.LINE_AA)

#     return output_frame

In [147]:
# plt.figure(figsize=(10,10))
# plt.imshow(prob_viz(res, actions, image, colors))

In [148]:
# 1. New detection variables
# sequence = []
# sentence = []
# predictions = []
# threshold = 0.8

# cap = cv2.VideoCapture(0)
# # Set mediapipe model 
# with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
#     while cap.isOpened():

#         # Read feed
#         ret, frame = cap.read()

#         # Make detections
#         image, results = mediapipe_detection(frame, holistic)
#         print(results)
        
#         # Draw landmarks
#         draw_styled_landmarks(image, results)
        
#         # 2. Prediction logic
#         keypoints = extract_keypoints(results)
#         sequence.append(keypoints)
#         sequence = sequence[-30:]
        
#         if len(sequence) == 30:
#             res = model.predict(np.expand_dims(sequence, axis=0))[0]
#             print(actions[np.argmax(res)])
#             predictions.append(np.argmax(res))
            
            
#         #3. Viz logic
#             if np.unique(predictions[-10:])[0]==np.argmax(res): 
#                 if res[np.argmax(res)] > threshold: 
                    
#                     if len(sentence) > 0: 
#                         if actions[np.argmax(res)] != sentence[-1]:
#                             sentence.append(actions[np.argmax(res)])
#                     else:
#                         sentence.append(actions[np.argmax(res)])

#             if len(sentence) > 5: 
#                 sentence = sentence[-5:]

#             # Viz probabilities
#             image = prob_viz(res, actions, image, colors)
            
#         cv2.rectangle(image, (0,0), (640, 40), (245, 117, 16), -1)
#         cv2.putText(image, ' '.join(sentence), (3,30), 
#                        cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
        
#         # Show to screen
#         cv2.imshow('OpenCV Feed', image)

#         # Break gracefully
#         if cv2.waitKey(10) & 0xFF == ord('q'):
#             break
#     cap.release()
#     cv2.destroyAllWindows()

In [149]:
# cap.release()
# cv2.destroyAllWindows()